apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oversea-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: "oversea-certificate"
    networking.gke.io/v1beta1.FrontendConfig: "oversea-frontend-config"
spec:
  rules:
    - host: team4.cs144.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oversea-service
                port:
                  number: 80
